# Generated by Django 4.2.1 on 2023-05-25 17:19

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admissionform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=300)),
                ('massage', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1000)),
                ('ct_slug', autoslug.fields.AutoSlugField(default='', editable=False, max_length=800, populate_from='category', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=300)),
                ('commnet', models.TextField(max_length=200)),
                ('checkbtn', models.BooleanField(verbose_name='Show this comment')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('massage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Onlin_apply_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(blank=True, max_length=300, null=True)),
                ('massage', models.TextField(blank=True, max_length=300, null=True)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='media/user_admison/')),
            ],
        ),
        migrations.CreateModel(
            name='Quick_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.FileField(upload_to='letestblog/')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_alt_name', models.CharField(max_length=500)),
                ('blog_meta_discreption', models.CharField(max_length=500, null=True)),
                ('blog_meta_keyword', models.CharField(max_length=500, null=True)),
                ('blog_small_content', froala_editor.fields.FroalaField()),
                ('blog_content', froala_editor.fields.FroalaField()),
                ('blog_url', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, max_length=1000, populate_from='blog_url', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed_app.category')),
            ],
        ),
    ]
