# Generated by Django 4.2.1 on 2023-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='author',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_post',
            name='blog_hesed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
