# Generated by Django 4.2.1 on 2023-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_app', '0002_blog_post_author_blog_post_blog_hesed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_meta_keyword',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
