# Generated by Django 4.2.1 on 2023-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_app', '0003_alter_blog_post_blog_meta_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='blog_meta_og_discreption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_meta_discreption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
