# Generated by Django 4.2.1 on 2023-05-29 14:08

import autoslug.fields
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ed_app', '0004_blog_post_blog_meta_og_discreption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Html_maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slect_html_page', models.CharField(choices=[('Top MBBS Colleges in Hyderabad', 'Top MBBS Colleges in Hyderabad'), ('Top MBBS Colleges in Pune', 'Top MBBS Colleges in Pune')], max_length=500)),
                ('page_title', models.CharField(max_length=550)),
                ('meta_discreption', models.CharField(blank=True, max_length=500, null=True)),
                ('first_heding', models.CharField(max_length=100)),
                ('bog_box_image', models.ImageField(upload_to='htmlpage')),
                ('image_alt_name', models.CharField(max_length=450)),
                ('post_title', models.TextField()),
                ('small_description', froala_editor.fields.FroalaField()),
                ('description', froala_editor.fields.FroalaField()),
                ('date', models.DateField()),
                ('htmlbcslug', autoslug.fields.AutoSlugField(default='', editable=False, max_length=1000, populate_from='post_title', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_image',
            field=models.ImageField(upload_to='letestblog/'),
        ),
    ]
