# Generated by Django 4.2.1 on 2023-05-29 14:47

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ed_app', '0005_html_maker_alter_blog_post_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_catrgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_page_name', models.CharField(choices=[('Top MBBS Colleges in Hyderabad', 'Top MBBS Colleges in Hyderabad'), ('Top MBBS Colleges in Pune', 'Top MBBS Colleges in Pune')], max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='html_maker',
            old_name='first_heding',
            new_name='first_heding_h1tag',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='bog_box_image',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='description',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='htmlbcslug',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='image_alt_name',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='meta_discreption',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='post_title',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='slect_html_page',
        ),
        migrations.RemoveField(
            model_name='html_maker',
            name='small_description',
        ),
        migrations.CreateModel(
            name='html_blogs_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=550)),
                ('post_image', models.ImageField(upload_to='html_page/')),
                ('post_title', models.CharField(max_length=250)),
                ('post_alt_name', models.CharField(max_length=500)),
                ('post_meta_discreption', models.CharField(blank=True, max_length=500, null=True)),
                ('small_description', froala_editor.fields.FroalaField()),
                ('description', froala_editor.fields.FroalaField()),
                ('date', models.DateField()),
                ('htmlbcslug', autoslug.fields.AutoSlugField(default='', editable=False, max_length=1000, populate_from='post_title', unique=True)),
                ('pg_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed_app.page_catrgery')),
            ],
        ),
        migrations.AddField(
            model_name='html_maker',
            name='slect_web_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ed_app.page_catrgery'),
            preserve_default=False,
        ),
    ]
