# Generated by Django 4.2.1 on 2023-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_app', '0006_page_catrgery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_catrgery',
            name='html_page_name',
            field=models.CharField(max_length=500),
        ),
    ]
