# Generated by Django 4.2.1 on 2023-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_app', '0007_alter_page_catrgery_html_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='html_blogs_post',
            name='small_description',
        ),
        migrations.AddField(
            model_name='html_maker',
            name='meta_des',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
